# Generated by Django 5.1.4 on 2025-01-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_menuitem_available_menuitem_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='restaurant_id',
            field=models.IntegerField(default=1),
        ),
    ]
