# Generated by Django 5.1.4 on 2025-01-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_order_orderitem_order_menu_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='name',
        ),
    ]
