# Generated by Django 5.1.4 on 2025-01-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_rename_menu_item_orderitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='name',
            new_name='menu_item',
        ),
    ]
